### ISSUE TITLE
Build hangs after Location prompt

### ISSUE THREAD

**Issue by Henchman-21** [biofects/Drobo-Status#1]
Trying to build container to be used for passing data over to HomeAssistant.  Cloned the repo and building using the dockerfile I'm getting a hang right after the locality prompt.  Tried using 11, 11. US, US, etc and never moves forward.

~~~
Setting up libsasl2-modules-db:amd64 (2.1.27+dfsg2-3ubuntu1) ...
Setting up tzdata (2022g-0ubuntu0.22.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa   3. Antarctica  5. Arctic  7. Atlantic  9. Indian    11. US
  2. America  4. Australia   6. Asia    8. Europe    10. Pacific  12. Etc
Geographic area: US
11. US

~~~

**Comment by biofects** [comment]
Hello,
What python version, and os version as well as which Drobo do you have? I have not seen this error. I want to try to reproduce it.

**Comment by Henchman-21** [comment]
Thanks for getting back to me!  

Running Python 3.8.10, on an Intel NUC running Ubuntu 20.04.5 LTS (Focal) trying to parse data on an 8 bay Drobo 810n.

**Comment by Henchman-21** [comment]
Thanks for getting back to me!

Running Python 3.8.10, on an Intel NUC running Ubuntu 20.04.5 LTS (Focal) trying to parse data on an 8 bay Drobo 810n.

**Comment by biofects** [comment]
OK, after quick look Docker isn't getting your local tzdata. 
Add this to the Docker file after line 2
`ENV TZ=America/Chicago

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone`

The please try to build again.

Please note you can change the TZ to a more specific location listed [Here](https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones) .

**Comment by Henchman-21** [comment]
Thanks, that seems to have pushed me forward!

Changed it to America/New_York, indeed seems to build now.  Was able to get the container to start, it looks like it's correctly pointed to port 5000/tcp from an internal port of 49153  but getting a refuse to connect when trying by browser.  Gonna poke around for a few and see if I'm missing anything obvious.  I've got ~25 other containers running fine so I know it's not an issue w/ Docker or the overall environment.

Container logs look like 
```
 * Serving Flask app 'drobo-status' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * ~~~
 *

**Comment by Henchman-21** [comment]
Actually, weirdly hitting that 49153 it seems to return the correct results.  Guessing it's a mapping issue on my side so I'll tinker with it.  Appreciate the help!

**Comment by biofects** [comment]
Awesome, thanks for update. Let me know if you need any further assistance.

**Comment by Henchman-21** [comment]
Thanks, maybe one more thing (though unrelated to the beginning of this thread.  You mention loading this via Scrape integration?  I've not used Scrape before, but adding the integration, the wizard is running through individual fields for headers, and other fields which seems different than adding the code you mentioned adding to configuration.  Can I just paste this (updated w/ relevant IP/etc) into my configuration.yaml to populate the sensor. entities?
<img width="488" alt="image" src="https://user-images.githubusercontent.com/4683381/210279550-1bacc136-f601-4c7d-9221-bf52e46786c8.png">

vs...

~~~
platform: rest
    name: tfam-storage
    # This is the ip of the host running drobo-status.py
    resource: http://192.168.1.126:5000
    json_attributes:
      - name
      - serial
      - firmware
      - disk-total
      - disk-used
      - disk-free
    value_template: "OK"
  - platform: template
    sensors:
      storage_name:
        value_template: "{{ state_attr('sensor.tfam-storage', 'name')['name'] }}"
      storage_serial:
        value_template: "{{ state_attr('sensor.tfam-storage', 'serial')['serial'] }}"
      storage_firmware:
        value_template: "{{ state_attr('sensor.tfam-storage', 'firmware')['firmware'] }}"
      storage_disk_total:
        value_template: "{{ state_attr('sensor.tfam-storage', 'disk-total')['disk-total'] }}"
~~~

**Comment by biofects** [comment]
Ah yes, I just added the code to my configuration file as well.

**Comment by Henchman-21** [comment]
Ah ok gotcha.  So I don't need to add via scrape integration or anything?   I'll try formatting for my configuration.yaml and give that a go. Thanks!

**Comment by Henchman-21** [comment]
Yep, put this under my sensors: section in my configuration.yaml and I'm able to pull the data through as sensors into HomeAssistant.  Thanks a million for your quick help, I love that I can add yet another crucial data source into my HA system.

**Comment by biofects** [comment]
Awesome, I'm glad it worked for you. If you have other integration idea
please let me know.
